### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by Samanw** [medbenji/MyProfile#58]
getting error 
1366 - Incorrect integer value: '' for column 'candeleteowncomments' at row 1

at

UPDATE mybb_usergroups SET `type`=1, `title`='ناظر', `description`='ناظر', `namestyle`='<span style=\"color: #674172; background: url(http://ani-dl.ws/otherimg/Tags2/rc599e.gif) right 7px;\"><strong>{username}</strong></span>', `usertitle`='Super Moderator', `stars`=0, `starimage`='', `image`='http://ani-dl.ws/otherimg/Tags2/Modirz_Kolz_M.png', `isbannedgroup`=0, `canview`=1, `canviewthreads`=1, `canviewprofiles`=1, `candlattachments`=1, `canviewboardclosed`=0, `canpostthreads`=1, `canpostreplys`=1, `canpostattachments`=1, `canratethreads`=1, `modposts`=0, `modthreads`=0, `mod_edit_posts`=0, `modattachments`=0, `caneditposts`=1, `candeleteposts`=1, `candeletethreads`=1, `caneditattachments`=1, `canpostpolls`=1, `canvotepolls`=1, `canundovotes`=1, `canusepms`=1, `cansendpms`=1, `cantrackpms`=1, `candenypmreceipts`=1, `pmquota`=500, `maxpmrecipients`=5, `cansendemail`=1, `cansendemailoverride`=1, `maxemails`=0, `emailfloodtime`=0, `canviewmemberlist`=1, `canviewcalendar`=1, `canaddevents`=1, `canbypasseventmod`=0, `canmoderateevents`=1, `canviewonline`=1, `canviewwolinvis`=1, `canviewonlineips`=1, `cancp`=0, `issupermod`=1, `cansearch`=1, `canusercp`=1, `canuploadavatars`=1, `canchangename`=1, `canbereported`=1, `canchangewebsite`=1, `showforumteam`=1, `usereputationsystem`=1, `cangivereputations`=1, `candeletereputations`=1, `reputationpower`=5, `maxreputationsday`=0, `maxreputationsperuser`=0, `maxreputationsperthread`=0, `attachquota`=0, `cancustomtitle`=1, `canwarnusers`=1, `canreceivewarnings`=1, `maxwarningsday`=3, `canmodcp`=1, `showinbirthdaylist`=1, `canoverridepm`=1, `canusesig`=1, `canusesigxposts`=0, `signofollow`=0, `edittimelimit`=0, `maxposts`=0, `showmemberlist`=1, `canmanageannounce`=1, `canmanagemodqueue`=1, `canmanagereportedcontent`=1, `canviewmodlogs`=1, `caneditprofiles`=0, `canbanusers`=1, `canviewwarnlogs`=1, `canuseipsearch`=0, `canviewarcade`=1, `canplayarcade`=1, `maxplaysday`=0, `canrategames`=1, `cansearchgames`=1, `canviewgamestats`=1, `canmoderategames`=1, `canviewtournaments`=1, `canjointournaments`=1, `cancreatetournaments`=1, `maxtournamentsday`=0, `canmanagecomments`=1, `cansendcomments`=1, `caneditowncomments`=1, `candeleteowncomments`='', `commentsperday`=0 WHERE gid='6'

**Comment by medbenji** [comment]
Not related to MyProfile itself.
