### ISSUE TITLE
Can't load mod: Fatal error on line 70

### ISSUE THREAD

**Issue by Flavius12** [medbenji/MyProfile#59]
I can't load and enable this plugin on mybb: I get this error:
*Fatal error: Class MyProfileCommentsMyAlertsFormatter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (MybbStuff_MyAlerts_Formatter_AbstractFormatter::buildShowLink) in inc/plugins/myprofile/myprofilecomments.class.php on line 70*

**Comment by nollidnosnhoj** [comment]
Hey!

The MyProfile plugin is very outdated, and is not compatible to the latest version of MyAlerts.

There is a modified version of this plugin that is compatible with the MyAlerts plugin
http://community.mybb.com/thread-159969-post-1143348.html#pid1143348

It isn't perfect, but it'll do.

**Comment by medbenji** [comment]
Fixed, this was a nasty issue that I created in the beginning of MyProfile, thinking it would work when MyAlerts 2.0 comes out. Turns out it didn't :/
MyProfile 1.0 is out.
