### ISSUE TITLE
Double comments

### ISSUE THREAD

**Issue by IdolwSzutrab7** [medbenji/MyProfile#61]
Guys I don't know but this plugin double comments o.O When I try and new comment (even if someone else) then we have two the same comments. It is only on my theme? Or it is bug? It is possible to fix it?

**Comment by IdolwSzutrab7** [comment]
![zrzut ekranu 2015-09-06 09 35 33](https://cloud.githubusercontent.com/assets/2501014/9703388/c7069582-547a-11e5-849c-83de55a247a2.png)

**Comment by medbenji** [comment]
I'm not able to reproduce this bug, can I have a link to the board? I'd probably be able to debug the javascript on there;

**Comment by IdolwSzutrab7** [comment]
You can see the link on screenshot but it was whole time and I already don't have active this plugin. Probably I have to install it again. I will do it today so then you can check what you want.

**Comment by IdolwSzutrab7** [comment]
Hmm... It is weird. Now everything works good. I use Chrome now so maybe on Firefox it is this problem.

**Comment by medbenji** [comment]
Okay I'll check that. By the way a new version is out :)

**Comment by IdolwSzutrab7** [comment]
Oho, so maybe new version resolved my problem. I downloaded plugin from mybb site. Btw. you don't have create new user. I already have TEST account so you can use it if you want (login: TEST password: tester).
