### ISSUE TITLE
MY Profile Enabed makes entire website not load.

### ISSUE THREAD

**Issue by genusistimelord** [medbenji/MyProfile#63]
For some odd reason when my profile is enabled the entire website will not load if logged out. This is with the newest edition.

**Comment by medbenji** [comment]
Hey, I'm unable to reproduce that, could you please give me a link to your website? Or maybe some other plugins might be breaking it?

**Comment by genusistimelord** [comment]
NVM i believe it was another plugin causing the issue due to the order they where installed in. anyways thank you.
