### ISSUE TITLE
MariaDB Database Ereor on Query

### ISSUE THREAD

**Issue by primesoftware** [medbenji/MyProfile#77]
Hello all,
I've been getting an error in the SQL synatx for the myprofilecomments.class.php script. Line 1146 reads:

```
$fields = "COUNT(*) AS rows";
```

"rows" is apparently a keyword in MariaDB at least so the above line should read:

```
$fields = "COUNT(*) AS `rows`";
```

Make sure those backticks are surrounding the "rows" keyword. Just an FYI.

**Comment by bls1999** [comment]
#81

**Comment by bls1999** [comment]
#81

**Comment by medbenji** [comment]
Hello, I honestly think MyProfile needs a rewrite. A fresh start, I will try to get back at you guys with something fresher than this buggy version

**Comment by medbenji** [comment]
Merged
