### ISSUE TITLE
I can't install MyProfile

### ISSUE THREAD

**Issue by Skadro** [medbenji/MyProfile#82]
Hello,
Im trying to install MyProfile but i can't because results an error.
EDIT: Now i downloded this files with fixed MariaDB error but I still can not
![myprofile](https://user-images.githubusercontent.com/24866668/38944465-9c16fde0-433c-11e8-8e37-831fec0cf67d.PNG)

**Comment by liicna** [comment]
i have the same issue yet i found no way to fix this

**Comment by bls1999** [comment]
@Skadro @liicna #84 should fix the issue. If you can't wait for the pull, you can make the change I made in `myprofileutils.class.php`.
